/* Generated by re2c 4.5.1 */


#include <stdlib.h>
#include "ext_scanners.h"

bufsize_t _ext_scan_at(bufsize_t (*scanner)(const unsigned char *), unsigned char *ptr, int len, bufsize_t offset)
{
	bufsize_t res;

        if (ptr == NULL || offset >= len) {
          return 0;
        } else {
	  unsigned char lim = ptr[len];

	  ptr[len] = '\0';
	  res = scanner(ptr + offset);
	  ptr[len] = lim;
        }

	return res;
}



bufsize_t _scan_table_start(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,
      0,  64,   0,  64,  64,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     64,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0, 128,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = *p;
  if (yych <= ' ') {
    if (yych <= '\n') {
      if (yych == '\t') goto yy2;
    } else {
      if (yych <= '\f') goto yy2;
      if (yych >= ' ') goto yy2;
    }
  } else {
    if (yych <= '9') {
      if (yych == '-') goto yy3;
    } else {
      if (yych <= ':') goto yy4;
      if (yych == '|') goto yy2;
    }
  }
  ++p;
yy1:
  { return 0; }
yy2:
  yych = *(marker = ++p);
  if (yybm[0+yych] & 64) goto yy5;
  if (yych == '-') goto yy7;
  if (yych == ':') goto yy8;
  goto yy1;
yy3:
  yych = *(marker = ++p);
  if (yybm[0+yych] & 128) goto yy7;
  if (yych <= ' ') {
    if (yych <= 0x08) goto yy1;
    if (yych <= '\r') goto yy10;
    if (yych <= 0x1F) goto yy1;
    goto yy10;
  } else {
    if (yych <= ':') {
      if (yych <= '9') goto yy1;
      goto yy9;
    } else {
      if (yych == '|') goto yy10;
      goto yy1;
    }
  }
yy4:
  yych = *(marker = ++p);
  if (yybm[0+yych] & 128) goto yy7;
  goto yy1;
yy5:
  yych = *++p;
  if (yybm[0+yych] & 64) goto yy5;
  if (yych == '-') goto yy7;
  if (yych == ':') goto yy8;
yy6:
  p = marker;
  goto yy1;
yy7:
  yych = *++p;
  if (yybm[0+yych] & 128) goto yy7;
  if (yych <= 0x1F) {
    if (yych <= '\n') {
      if (yych <= 0x08) goto yy6;
      if (yych <= '\t') goto yy9;
      goto yy11;
    } else {
      if (yych <= '\f') goto yy9;
      if (yych <= '\r') goto yy12;
      goto yy6;
    }
  } else {
    if (yych <= ':') {
      if (yych <= ' ') goto yy9;
      if (yych <= '9') goto yy6;
      goto yy9;
    } else {
      if (yych == '|') goto yy13;
      goto yy6;
    }
  }
yy8:
  yych = *++p;
  if (yybm[0+yych] & 128) goto yy7;
  goto yy6;
yy9:
  yych = *++p;
yy10:
  if (yych <= '\r') {
    if (yych <= '\t') {
      if (yych <= 0x08) goto yy6;
      goto yy9;
    } else {
      if (yych <= '\n') goto yy11;
      if (yych <= '\f') goto yy9;
      goto yy12;
    }
  } else {
    if (yych <= ' ') {
      if (yych <= 0x1F) goto yy6;
      goto yy9;
    } else {
      if (yych == '|') goto yy13;
      goto yy6;
    }
  }
yy11:
  ++p;
  {
      return (bufsize_t)(p - start);
    }
yy12:
  yych = *++p;
  if (yych == '\n') goto yy11;
  goto yy6;
yy13:
  yych = *++p;
  if (yybm[0+yych] & 128) goto yy7;
  if (yych <= '\r') {
    if (yych <= '\t') {
      if (yych <= 0x08) goto yy6;
      goto yy13;
    } else {
      if (yych <= '\n') goto yy11;
      if (yych <= '\f') goto yy13;
      goto yy12;
    }
  } else {
    if (yych <= ' ') {
      if (yych <= 0x1F) goto yy6;
      goto yy13;
    } else {
      if (yych == ':') goto yy8;
      goto yy6;
    }
  }
}

}

bufsize_t _scan_table_cell(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  unsigned int yyaccept = 0;
  static const unsigned char yybm[256] = {
      0,  64,  64,  64,  64,  64,  64,  64,
     64,  64,   0,  64,  64,   0,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64, 128,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,   0,  64,  64,  64,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = *p;
  if (yybm[0+yych] & 64) goto yy17;
  if (yych <= 0xE0) {
    if (yych <= '\\') {
      if (yych >= 0x0E) goto yy19;
    } else {
      if (yych <= 0xC1) goto yy15;
      if (yych <= 0xDF) goto yy20;
      goto yy21;
    }
  } else {
    if (yych <= 0xF0) {
      if (yych <= 0xEF) goto yy22;
      goto yy23;
    } else {
      if (yych <= 0xF3) goto yy24;
      if (yych <= 0xF4) goto yy25;
    }
  }
yy15:
  ++p;
yy16:
  { return 0; }
yy17:
  yyaccept = 0;
  yych = *(marker = ++p);
  if (yybm[0+yych] & 64) goto yy17;
  if (yych <= 0xE0) {
    if (yych <= '\\') {
      if (yych >= 0x0E) goto yy19;
    } else {
      if (yych <= 0xC1) goto yy18;
      if (yych <= 0xDF) goto yy26;
      goto yy28;
    }
  } else {
    if (yych <= 0xF0) {
      if (yych <= 0xEF) goto yy29;
      goto yy30;
    } else {
      if (yych <= 0xF3) goto yy31;
      if (yych <= 0xF4) goto yy32;
    }
  }
yy18:
  { return (bufsize_t)(p - start); }
yy19:
  yyaccept = 0;
  yych = *(marker = ++p);
  if (yybm[0+yych] & 128) goto yy19;
  if (yych <= 0xC1) {
    if (yych <= '\n') {
      if (yych <= 0x00) goto yy18;
      if (yych <= '\t') goto yy17;
      goto yy18;
    } else {
      if (yych == '\r') goto yy18;
      if (yych <= 0x7F) goto yy17;
      goto yy18;
    }
  } else {
    if (yych <= 0xEF) {
      if (yych <= 0xDF) goto yy26;
      if (yych <= 0xE0) goto yy28;
      goto yy29;
    } else {
      if (yych <= 0xF0) goto yy30;
      if (yych <= 0xF3) goto yy31;
      if (yych <= 0xF4) goto yy32;
      goto yy18;
    }
  }
yy20:
  yych = *++p;
  if (yych <= 0x7F) goto yy16;
  if (yych <= 0xBF) goto yy17;
  goto yy16;
yy21:
  yyaccept = 1;
  yych = *(marker = ++p);
  if (yych <= 0x9F) goto yy16;
  if (yych <= 0xBF) goto yy26;
  goto yy16;
yy22:
  yyaccept = 1;
  yych = *(marker = ++p);
  if (yych <= 0x7F) goto yy16;
  if (yych <= 0xBF) goto yy26;
  goto yy16;
yy23:
  yyaccept = 1;
  yych = *(marker = ++p);
  if (yych <= 0x8F) goto yy16;
  if (yych <= 0xBF) goto yy29;
  goto yy16;
yy24:
  yyaccept = 1;
  yych = *(marker = ++p);
  if (yych <= 0x7F) goto yy16;
  if (yych <= 0xBF) goto yy29;
  goto yy16;
yy25:
  yyaccept = 1;
  yych = *(marker = ++p);
  if (yych <= 0x7F) goto yy16;
  if (yych <= 0x8F) goto yy29;
  goto yy16;
yy26:
  yych = *++p;
  if (yych <= 0x7F) goto yy27;
  if (yych <= 0xBF) goto yy17;
yy27:
  p = marker;
  if (yyaccept == 0) goto yy18;
  else goto yy16;
yy28:
  yych = *++p;
  if (yych <= 0x9F) goto yy27;
  if (yych <= 0xBF) goto yy26;
  goto yy27;
yy29:
  yych = *++p;
  if (yych <= 0x7F) goto yy27;
  if (yych <= 0xBF) goto yy26;
  goto yy27;
yy30:
  yych = *++p;
  if (yych <= 0x8F) goto yy27;
  if (yych <= 0xBF) goto yy29;
  goto yy27;
yy31:
  yych = *++p;
  if (yych <= 0x7F) goto yy27;
  if (yych <= 0xBF) goto yy29;
  goto yy27;
yy32:
  yych = *++p;
  if (yych <= 0x7F) goto yy27;
  if (yych <= 0x8F) goto yy29;
  goto yy27;
}

}

bufsize_t _scan_table_cell_end(const unsigned char *p)
{
  const unsigned char *start = p;
  
{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,
      0, 128,   0, 128, 128,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    128,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = *p;
  if (yych == '|') goto yy34;
  ++p;
  { return 0; }
yy34:
  yych = *++p;
  if (yybm[0+yych] & 128) goto yy34;
  { return (bufsize_t)(p - start); }
}

}

bufsize_t _scan_table_row_end(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,
      0, 128,   0, 128, 128,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    128,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = *p;
  if (yych <= '\f') {
    if (yych <= 0x08) goto yy36;
    if (yych == '\n') goto yy39;
    goto yy38;
  } else {
    if (yych <= '\r') goto yy40;
    if (yych == ' ') goto yy38;
  }
yy36:
  ++p;
yy37:
  { return 0; }
yy38:
  yych = *(marker = ++p);
  if (yych <= 0x08) goto yy37;
  if (yych <= '\r') goto yy42;
  if (yych == ' ') goto yy42;
  goto yy37;
yy39:
  ++p;
  { return (bufsize_t)(p - start); }
yy40:
  yych = *++p;
  if (yych == '\n') goto yy39;
  goto yy37;
yy41:
  yych = *++p;
yy42:
  if (yybm[0+yych] & 128) goto yy41;
  if (yych <= 0x08) goto yy43;
  if (yych <= '\n') goto yy39;
  if (yych <= '\r') goto yy44;
yy43:
  p = marker;
  goto yy37;
yy44:
  yych = *++p;
  if (yych == '\n') goto yy39;
  goto yy43;
}

}

bufsize_t _scan_tasklist(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,
      0, 128,   0, 128, 128,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    128,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = *p;
  if (yych == '[') goto yy47;
  ++p;
yy46:
  { return 0; }
yy47:
  yych = *(marker = ++p);
  if (yych <= 'W') {
    if (yych != ' ') goto yy46;
  } else {
    if (yych <= 'X') goto yy48;
    if (yych != 'x') goto yy46;
  }
yy48:
  yych = *++p;
  if (yych == ']') goto yy50;
yy49:
  p = marker;
  goto yy46;
yy50:
  yych = *++p;
  if (yybm[0+yych] & 128) goto yy51;
  goto yy49;
yy51:
  yych = *++p;
  if (yybm[0+yych] & 128) goto yy51;
  { return (bufsize_t)(p - start); }
}

}

bufsize_t _scan_math_dollar_inline_open(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  if (yych == '$') goto yy53;
  ++p;
  { return 0; }
yy53:
  ++p;
  { return (bufsize_t)(p - start); }
}

}

bufsize_t _scan_math_dollar_backtick_open(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  if (yych == '$') goto yy56;
  ++p;
yy55:
  { return 0; }
yy56:
  yych = *++p;
  if (yych != '`') goto yy55;
  ++p;
  { return (bufsize_t)(p - start); }
}

}

bufsize_t _scan_math_dollar_display_open(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  if (yych == '$') goto yy59;
  ++p;
yy58:
  { return 0; }
yy59:
  yych = *++p;
  if (yych != '$') goto yy58;
  ++p;
  { return (bufsize_t)(p - start); }
}

}

bufsize_t _scan_math_backslash_inline_open(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  if (yych == '\\') goto yy62;
  ++p;
yy61:
  { return 0; }
yy62:
  yych = *(marker = ++p);
  if (yych == '(') goto yy63;
  if (yych == '\\') goto yy64;
  goto yy61;
yy63:
  ++p;
  { return (bufsize_t)(p - start); }
yy64:
  yych = *++p;
  if (yych == '(') goto yy63;
  p = marker;
  goto yy61;
}

}

bufsize_t _scan_math_backslash_display_open(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  if (yych == '\\') goto yy67;
  ++p;
yy66:
  { return 0; }
yy67:
  yych = *(marker = ++p);
  if (yych <= 'Z') goto yy66;
  if (yych <= '[') goto yy68;
  if (yych <= '\\') goto yy69;
  goto yy66;
yy68:
  ++p;
  { return (bufsize_t)(p - start); }
yy69:
  yych = *++p;
  if (yych == '[') goto yy68;
  p = marker;
  goto yy66;
}

}
